var N = null;var sourcesIndex = {};
sourcesIndex["db"] = {"name":"","dirs":[{"name":"cache_structures","files":["mod.rs","socket.rs"]}],"files":["cache.rs","clients.rs","lib.rs","schema.rs","utils.rs"]};
sourcesIndex["muoxi_benchmarks"] = {"name":"","files":["io.rs","main.rs","report.rs"]};
sourcesIndex["muoxi_engine"] = {"name":"","files":["muoxi.rs"]};
sourcesIndex["muoxi_sandbox"] = {"name":"","files":["main.rs"]};
sourcesIndex["muoxi_staging"] = {"name":"","files":["cmds.rs","comms.rs","copyover.rs","prelude.rs","staging_proxy.rs","states.rs"]};
sourcesIndex["muoxi_watchdog"] = {"name":"","files":["watchdog.rs"]};
sourcesIndex["muoxi_web"] = {"name":"","files":["webserver.rs"]};
sourcesIndex["states"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
