(function() {var implementors = {};
implementors["db"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"db/templates/struct.ClientDB.html\" title=\"struct db::templates::ClientDB\">ClientDB</a>",synthetic:false,types:["db::templates::ClientDB"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"db/templates/struct.Character.html\" title=\"struct db::templates::Character\">Character</a>",synthetic:false,types:["db::templates::Character"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"db/struct.DatabaseHandler.html\" title=\"struct db::DatabaseHandler\">DatabaseHandler</a>",synthetic:false,types:["db::DatabaseHandler"]},];
implementors["muoxi_staging"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"muoxi_staging/connstates/enum.ConnState.html\" title=\"enum muoxi_staging::connstates::ConnState\">ConnState</a>",synthetic:false,types:["muoxi_staging::connstates::ConnState"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"muoxi_staging/connstates/struct.AwaitingAcctName.html\" title=\"struct muoxi_staging::connstates::AwaitingAcctName\">AwaitingAcctName</a>",synthetic:false,types:["muoxi_staging::connstates::AwaitingAcctName"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"muoxi_staging/connstates/struct.NewAcctName.html\" title=\"struct muoxi_staging::connstates::NewAcctName\">NewAcctName</a>",synthetic:false,types:["muoxi_staging::connstates::NewAcctName"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"muoxi_staging/connstates/struct.MainMenu.html\" title=\"struct muoxi_staging::connstates::MainMenu\">MainMenu</a>",synthetic:false,types:["muoxi_staging::connstates::MainMenu"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"muoxi_staging/connstates/struct.EnterGame.html\" title=\"struct muoxi_staging::connstates::EnterGame\">EnterGame</a>",synthetic:false,types:["muoxi_staging::connstates::EnterGame"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"muoxi_staging/connstates/struct.Next.html\" title=\"struct muoxi_staging::connstates::Next\">Next</a>",synthetic:false,types:["muoxi_staging::connstates::Next"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"muoxi_staging/connstates/struct.NewAcct.html\" title=\"struct muoxi_staging::connstates::NewAcct\">NewAcct</a>",synthetic:false,types:["muoxi_staging::connstates::NewAcct"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"muoxi_staging/connstates/enum.ConnStateMessages.html\" title=\"enum muoxi_staging::connstates::ConnStateMessages\">ConnStateMessages</a>",synthetic:false,types:["muoxi_staging::connstates::ConnStateMessages"]},];
implementors["muoxi_watchdog"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"muoxi_watchdog/enum.JsonFile.html\" title=\"enum muoxi_watchdog::JsonFile\">JsonFile</a>",synthetic:false,types:["muoxi_watchdog::JsonFile"]},];
implementors["muoxi_web"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"muoxi_web/struct.ClientData.html\" title=\"struct muoxi_web::ClientData\">ClientData</a>",synthetic:false,types:["muoxi_web::ClientData"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"muoxi_web/struct.Clients.html\" title=\"struct muoxi_web::Clients\">Clients</a>",synthetic:false,types:["muoxi_web::Clients"]},];
implementors["states"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"states/enum.ConnStates.html\" title=\"enum states::ConnStates\">ConnStates</a>",synthetic:false,types:["states::ConnStates"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()