(function() {var implementors = {};
implementors["db"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"db/clients/struct.Client.html\" title=\"struct db::clients::Client\">Client</a>","synthetic":false,"types":["db::clients::Client"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"db/schema/clients/struct.table.html\" title=\"struct db::schema::clients::table\">table</a>","synthetic":false,"types":["db::schema::clients::table"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"db/schema/clients/columns/struct.star.html\" title=\"struct db::schema::clients::columns::star\">star</a>","synthetic":false,"types":["db::schema::clients::columns::star"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"db/schema/clients/columns/struct.uid.html\" title=\"struct db::schema::clients::columns::uid\">uid</a>","synthetic":false,"types":["db::schema::clients::columns::uid"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"db/schema/clients/columns/struct.ip.html\" title=\"struct db::schema::clients::columns::ip\">ip</a>","synthetic":false,"types":["db::schema::clients::columns::ip"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"db/schema/clients/columns/struct.port.html\" title=\"struct db::schema::clients::columns::port\">port</a>","synthetic":false,"types":["db::schema::clients::columns::port"]}];
implementors["muoxi_benchmarks"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"muoxi_benchmarks/io/struct.Person.html\" title=\"struct muoxi_benchmarks::io::Person\">Person</a>","synthetic":false,"types":["muoxi_benchmarks::io::Person"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"muoxi_benchmarks/report/struct.ReportBuilder.html\" title=\"struct muoxi_benchmarks::report::ReportBuilder\">ReportBuilder</a>","synthetic":false,"types":["muoxi_benchmarks::report::ReportBuilder"]}];
implementors["muoxi_sandbox"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"muoxi_sandbox/struct.Person.html\" title=\"struct muoxi_sandbox::Person\">Person</a>","synthetic":false,"types":["muoxi_sandbox::Person"]}];
implementors["muoxi_staging"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"muoxi_staging/cmds/proxy_commands/struct.CmdProxyNew.html\" title=\"struct muoxi_staging::cmds::proxy_commands::CmdProxyNew\">CmdProxyNew</a>","synthetic":false,"types":["muoxi_staging::cmds::proxy_commands::CmdProxyNew"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"muoxi_staging/cmds/proxy_commands/struct.CmdProxyAccount.html\" title=\"struct muoxi_staging::cmds::proxy_commands::CmdProxyAccount\">CmdProxyAccount</a>","synthetic":false,"types":["muoxi_staging::cmds::proxy_commands::CmdProxyAccount"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"muoxi_staging/states/enum.ConnStates.html\" title=\"enum muoxi_staging::states::ConnStates\">ConnStates</a>","synthetic":false,"types":["muoxi_staging::states::ConnStates"]}];
implementors["muoxi_watchdog"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"muoxi_watchdog/enum.JsonFile.html\" title=\"enum muoxi_watchdog::JsonFile\">JsonFile</a>","synthetic":false,"types":["muoxi_watchdog::JsonFile"]}];
implementors["muoxi_web"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"muoxi_web/struct.ClientData.html\" title=\"struct muoxi_web::ClientData\">ClientData</a>","synthetic":false,"types":["muoxi_web::ClientData"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"muoxi_web/struct.Clients.html\" title=\"struct muoxi_web::Clients\">Clients</a>","synthetic":false,"types":["muoxi_web::Clients"]}];
implementors["states"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"states/enum.ConnStates.html\" title=\"enum states::ConnStates\">ConnStates</a>","synthetic":false,"types":["states::ConnStates"]}];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()